### ISSUE TITLE
Log capturing and storing

### ISSUE THREAD

**Issue by DemetreJou** [DemetreJou/TeamRocket#14]
Setup logging serve to accept log requests, store into db
way to link requests that come from different sources that have same request_id or other identifier

Entire ticket should be done end of the Nov 29th

- [x] https://github.com/DemetreJou/TeamRocket/issues/33 Nov 24th

- [x] https://github.com/DemetreJou/TeamRocket/issues/34 Nov 26th 

- [x] https://github.com/DemetreJou/TeamRocket/issues/35 Nov 28th

**Comment by sultansidhu** [comment]
Will be done in two parts, first being creating the log class, and the second being creating a connection with the database.

**Comment by DemetreJou** [comment]
Closed since all sub issues are closed
