### ISSUE TITLE
Setup orm with db

### ISSUE THREAD

**Issue by DemetreJou** [DemetreJou/TeamRocket#33]
Have prisma working with psql and express
Setup log message model, migration,

**Comment by sultansidhu** [comment]
First step - creating ORM migration for the database and hooking it up with the logger class
Second step - iron out the ORM, creation of migration for changing the time datatype to TIMESTAMP

**Comment by sultansidhu** [comment]
### Use these steps to test out the connection to the database
- npx prisma migrate dev --name init
- npm run build
- npm start
> These commands should build the containers, start up the connection, and run the `demo.ts` file. The file is intended to be a test for the database connectivity.
